name: 'Setup Misc Configs'
description: 'Set up kernel configuration fragment with miscellaneous options'
inputs:
  version:
    description: 'Kernel config version (e.g., android14-6.12)'
    required: true
  kernel_version:
    description: 'Kernel version (e.g., 6.1)'
    required: true
  android_version:
    description: 'Android version (e.g., android14)'
    required: true
  sublevel:
    description: 'Sublevel of kernel version (e.g., 1)'
    required: true
  variant:
    description: 'Build variant (Normal, Bypass, Wild, boot-time)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Enable Kernel Configs
      uses: ./.github/actions/set-kernel-config
      with:
        config_list: |
          CONFIG_OVERLAY_FS=y
          CONFIG_TMPFS_XATTR=y
          CONFIG_TMPFS_POSIX_ACL=y
          CONFIG_KALLSYMS=y
          CONFIG_KALLSYMS_ALL=y
          CONFIG_CFG80211=m
          CONFIG_CFG80211_REQUIRE_SIGNED_REGDB=y
          CONFIG_CFG80211_USE_KERNEL_REGDB_KEYS=y
          CONFIG_CFG80211_DEFAULT_PS=y
          CONFIG_CFG80211_CRDA_SUPPORT=y
          CONFIG_MAC80211=m
          CONFIG_MAC80211_HAS_RC=y
          CONFIG_MAC80211_RC_MINSTREL=y
          CONFIG_MAC80211_RC_DEFAULT_MINSTREL=y
          CONFIG_MAC80211_RC_DEFAULT="minstrel_ht"
          CONFIG_EEPROM_93CX6=m
          CONFIG_WLAN_VENDOR_RALINK=y
          CONFIG_RT2X00=m
          CONFIG_RT61PCI=m
          CONFIG_RT2500USB=m
          CONFIG_RT73USB=m
          CONFIG_RT2800USB=m
          CONFIG_RT2800USB_RT33XX=y
          CONFIG_RT2800USB_RT35XX=y
          CONFIG_RT2800USB_RT3573=y
          CONFIG_RT2800USB_RT53XX=y
          CONFIG_RT2800USB_RT55XX=y
          CONFIG_RT2800USB_UNKNOWN=y
          CONFIG_RT2800_LIB=m
          CONFIG_RT2X00_LIB_MMIO=m
          CONFIG_RT2X00_LIB_PCI=m
          CONFIG_RT2X00_LIB_USB=m
          CONFIG_RT2X00_LIB=m
          CONFIG_RT2X00_LIB_FIRMWARE=y
          CONFIG_RT2X00_LIB_CRYPTO=y
          CONFIG_RT2X00_LIB_LEDS=y
